In [7]:
import pandas as pd
from sqlalchemy import create_engine
from getpass import getpass # Recommended for securely entering passwords

# # --- 1. Create Example DataFrame (Same as before) ---
# data = {'col1': [1, 2, 3], 
#         'col2': ['A', 'B', 'C'], 
#         'date': pd.to_datetime(['2024-01-01', '2024-01-02', '2024-01-03'])}
# df = pd.DataFrame(data)

# --- 2. Define MySQL Connection Parameters ---
MYSQL_USER = "root"          # e.g., 'root'
MYSQL_PASS = getpass("Enter MySQL Password: ") # Securely prompts for password
MYSQL_HOST = "localhost"                # Or your server's IP
MYSQL_PORT = "3306"                     # Default MySQL port
MYSQL_DB = "phonepay"         # The schema/database you want to use

Enter MySQL Password:  ········

In [22]:
def CreateAndInsertData(TableName, DataFrame):
        
    # **CHANGE 1: Update the DATABASE_URL format for MySQL Connector**
    # Format: mysql+mysqlconnector://user:password@host:port/dbname
    DATABASE_URL = f"mysql+mysqlconnector://{MYSQL_USER}:{MYSQL_PASS}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB}"
    
    # Create the SQLAlchemy Engine
    try:
        # **CHANGE 2: Create the engine using the new MySQL URL**
        engine = create_engine(DATABASE_URL)
    except Exception as e:
        print(f"❌ Could not create the database engine: {e}")
        exit()

    
    try:
        print("Attempting to connect and store DataFrame...")
        
        DataFrame.to_sql(
            name=TableName,
            con=engine,
            if_exists='replace',  # Creates or replaces the table
            index=True,          # To write the DataFrame's index
            chunksize=1000        # Write in batches of 1000 rows
        )
        print(f"✅ DataFrame successfully stored to table '{TableName}' in MySQL.")
    
        # --- 4. Verify the Data (Optional) ---
        df_check = pd.read_sql(f"SELECT * FROM {TableName}", con=engine)
        print("\nData retrieved from database for verification:")
        print(df_check)
        
    except Exception as e:
        print(f"❌ An error occurred during database operation: {e}")

In [15]:
#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\aggregated\\transaction\\country\\india\\state\\"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'TransacionType':[], 'TransacionCount':[], 'TransacionAmount':[]}

In [16]:

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['TransacionType'].append(Name)
              clm['TransacionCount'].append(count)
              clm['TransacionAmount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [17]:
df

,State,Year,Quater,TransacionType,TransacionCount,TransacionAmount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [18]:
tn = "Aggregated_transaction"

In [23]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Aggregated_transaction' in MySQL.

Data retrieved from database for verification:
      index                      State  Year  Quater  \
0         0  andaman-&-nicobar-islands  2018       1
1         1  andaman-&-nicobar-islands  2018       1
2         2  andaman-&-nicobar-islands  2018       1
3         3  andaman-&-nicobar-islands  2018       1
4         4  andaman-&-nicobar-islands  2018       1
...     ...                        ...   ...     ...
5029   5029                west-bengal  2024       4
5030   5030                west-bengal  2024       4
5031   5031                west-bengal  2024       4
5032   5032                west-bengal  2024       4
5033   5033                west-bengal  2024       4

                TransacionType  TransacionCount  TransacionAmount
0     Recharge & bill payments             4200      1.845307e+06
1        Peer-to-peer payments             1871      1.213866e+07
2            Merchant payments              298      4.525072e+05
3           Financial Services               33      1.060142e+04
4                       Others              256      1.846899e+05
...                        ...              ...               ...
5029         Merchant payments        655100809      3.892862e+11
5030     Peer-to-peer payments        493217788      1.361927e+12
5031  Recharge & bill payments         76043195      5.753406e+10
5032        Financial Services          2352084      8.472965e+08
5033                    Others           421806      5.053641e+08

[5034 rows x 7 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Aggregated_transaction' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [27]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\aggregated\\insurance\\country\\india\\state\\"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'TransacionType':[], 'TransacionCount':[], 'TransacionAmount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['TransacionType'].append(Name)
              clm['TransacionCount'].append(count)
              clm['TransacionAmount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [28]:
df

,State,Year,Quater,TransacionType,TransacionCount,TransacionAmount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [29]:
tn = "Aggregated_insurance"

In [30]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Aggregated_insurance' in MySQL.

Data retrieved from database for verification:
     index                      State  Year  Quater TransacionType  \
0        0  andaman-&-nicobar-islands  2020       2      Insurance
1        1  andaman-&-nicobar-islands  2020       3      Insurance
2        2  andaman-&-nicobar-islands  2020       4      Insurance
3        3  andaman-&-nicobar-islands  2021       1      Insurance
4        4  andaman-&-nicobar-islands  2021       2      Insurance
..     ...                        ...   ...     ...            ...
677    677                west-bengal  2023       4      Insurance
678    678                west-bengal  2024       1      Insurance
679    679                west-bengal  2024       2      Insurance
680    680                west-bengal  2024       3      Insurance
681    681                west-bengal  2024       4      Insurance

     TransacionCount  TransacionAmount
0                  6            1360.0
1                 41           15380.0
2                124          157975.0
3                225          244266.0
4                137          181504.0
..               ...               ...
677            72712       100365562.0
678            79576       104987909.0
679            67048        89476633.0
680            77158       107451766.0
681            91719       120602777.0

[682 rows x 7 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Aggregated_insurance' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [42]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\aggregated\\user\\country\\india\\state\\"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'MobileBrand':[], 'UserCount':[], 'Percentage':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            #print(D['data']['usersByDevice'])
            # break

            if D.get('data').get('usersByDevice') :
                for z in D.get('data').get('usersByDevice'):
    
                  # print(z)
                  # import pdb
                  # pdb.set_trace()
                  brand = z.get('brand')
                  count = z.get('count')
                  percentage = z.get('percentage')
                  clm['MobileBrand'].append(brand)
                  #break
                  clm['UserCount'].append(count)
                  clm['Percentage'].append(percentage)
                  clm['State'].append(i)
                  clm['Year'].append(j)
                  clm['Quater'].append(int(k.strip('.json')))
                  
                  
            else:
                
                clm['MobileBrand'].append(None)
                #break
                clm['UserCount'].append(0)
                clm['Percentage'].append(0)
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))

#Succesfully created a dataframe
df=pd.DataFrame(clm)

SyntaxError: incomplete input (730293739.py, line 54)

In [38]:
df

,State,Year,Quater,MobileBrand,UserCount,Percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
7123,west-bengal,2023,4,None,0,0.000000
7124,west-bengal,2024,1,None,0,0.000000
7125,west-bengal,2024,2,None,0,0.000000
7126,west-bengal,2024,3,None,0,0.000000
7127,west-bengal,2024,4,None,0,0.000000

In [39]:
tn = "Aggregated_user"

In [41]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Aggregated_user' in MySQL.

Data retrieved from database for verification:
      index                      State  Year  Quater MobileBrand  UserCount  \
0         0  andaman-&-nicobar-islands  2018       1      Xiaomi       1665
1         1  andaman-&-nicobar-islands  2018       1     Samsung       1445
2         2  andaman-&-nicobar-islands  2018       1        Vivo        982
3         3  andaman-&-nicobar-islands  2018       1        Oppo        501
4         4  andaman-&-nicobar-islands  2018       1     OnePlus        332
...     ...                        ...   ...     ...         ...        ...
7123   7123                west-bengal  2023       4        None          0
7124   7124                west-bengal  2024       1        None          0
7125   7125                west-bengal  2024       2        None          0
7126   7126                west-bengal  2024       3        None          0
7127   7127                west-bengal  2024       4        None          0

      Percentage
0       0.247033
1       0.214392
2       0.145697
3       0.074332
4       0.049258
...          ...
7123    0.000000
7124    0.000000
7125    0.000000
7126    0.000000
7127    0.000000

[7128 rows x 7 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Aggregated_user' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [43]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\map\\transaction\\hover\\country\\india\\state\\"

map_state_list=os.listdir(path)
map_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'DistrictName':[], 'MetricType':[], 'MetricCount':[], 'MetricAmount':[]}

for i in map_state_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              metric_type = z['metric'][0]['type']
              clm['DistrictName'].append(Name)
              clm['MetricType'].append(metric_type)  
              clm['MetricCount'].append(count)
              clm['MetricAmount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [44]:
df

,State,Year,Quater,DistrictName,MetricType,MetricCount,MetricAmount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,TOTAL,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,TOTAL,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,TOTAL,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,TOTAL,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,TOTAL,9395,2.394824e+07
...,...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,TOTAL,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,TOTAL,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,TOTAL,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,TOTAL,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,TOTAL,67833775,1.142771e+11

In [45]:
tn = "Map_map"

In [46]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Map_map' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater  \
0          0  andaman-&-nicobar-islands  2018       1
1          1  andaman-&-nicobar-islands  2018       1
2          2  andaman-&-nicobar-islands  2018       1
3          3  andaman-&-nicobar-islands  2018       2
4          4  andaman-&-nicobar-islands  2018       2
...      ...                        ...   ...     ...
20599  20599                west-bengal  2024       4
20600  20600                west-bengal  2024       4
20601  20601                west-bengal  2024       4
20602  20602                west-bengal  2024       4
20603  20603                west-bengal  2024       4

                            DistrictName MetricType  MetricCount  MetricAmount
0      north and middle andaman district      TOTAL          442  9.316631e+05
1                 south andaman district      TOTAL         5688  1.256025e+07
2                      nicobars district      TOTAL          528  1.139849e+06
3      north and middle andaman district      TOTAL          825  1.317863e+06
4                 south andaman district      TOTAL         9395  2.394824e+07
...                                  ...        ...          ...           ...
20599                alipurduar district      TOTAL     15875637  2.099251e+10
20600         paschim bardhaman district      TOTAL     56616799  6.968735e+10
20601                     nadia district      TOTAL     65274337  1.079320e+11
20602                   birbhum district      TOTAL     36905213  5.778701e+10
20603           purba medinipur district      TOTAL     67833775  1.142771e+11

[20604 rows x 8 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Map_map' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [48]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\map\\insurance\\hover\\country\\india\\state\\"

map_state_list=os.listdir(path)
map_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'DistrictName':[], 'MetricType':[], 'MetricCount':[], 'MetricAmount':[]}

for i in map_state_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              metric_type = z['metric'][0]['type']
              clm['DistrictName'].append(Name)
              clm['MetricType'].append(metric_type)  
              clm['MetricCount'].append(count)
              clm['MetricAmount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [49]:
df

,State,Year,Quater,DistrictName,MetricType,MetricCount,MetricAmount
0,andaman-&-nicobar-islands,2020,2,south andaman district,TOTAL,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,TOTAL,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,TOTAL,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,TOTAL,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,TOTAL,5,1448.0
...,...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,TOTAL,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,TOTAL,4945,7005851.0
13873,west-bengal,2024,4,nadia district,TOTAL,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,TOTAL,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,TOTAL,3559,4439061.0

In [50]:
tn = "Map_insurance"

In [51]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Map_insurance' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater  \
0          0  andaman-&-nicobar-islands  2020       2
1          1  andaman-&-nicobar-islands  2020       2
2          2  andaman-&-nicobar-islands  2020       3
3          3  andaman-&-nicobar-islands  2020       3
4          4  andaman-&-nicobar-islands  2020       3
...      ...                        ...   ...     ...
13871  13871                west-bengal  2024       4
13872  13872                west-bengal  2024       4
13873  13873                west-bengal  2024       4
13874  13874                west-bengal  2024       4
13875  13875                west-bengal  2024       4

                            DistrictName MetricType  MetricCount  MetricAmount
0                 south andaman district      TOTAL            3         795.0
1                      nicobars district      TOTAL            3         565.0
2      north and middle andaman district      TOTAL            1         281.0
3                 south andaman district      TOTAL           35       13651.0
4                      nicobars district      TOTAL            5        1448.0
...                                  ...        ...          ...           ...
13871                alipurduar district      TOTAL         1023     1613143.0
13872         paschim bardhaman district      TOTAL         4945     7005851.0
13873                     nadia district      TOTAL         3807     5031294.0
13874                   birbhum district      TOTAL         1818     2423290.0
13875           purba medinipur district      TOTAL         3559     4439061.0

[13876 rows x 8 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Map_insurance' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [52]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\map\\user\\hover\\country\\india\\state\\"

map_state_list=os.listdir(path)
map_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'DistrictName':[], 'RegisteredUsers':[]}

for i in map_state_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D.get('data').get('hoverData').keys():
              #print(z)
              clm['DistrictName'].append(z)
              clm['RegisteredUsers'].append(D.get('data').get('hoverData').get(z).get('registeredUsers'))
              #clm['registeredUsers'].append(None)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))

df=pd.DataFrame(clm)

In [53]:
df

,State,Year,Quater,DistrictName,RegisteredUsers
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846
2,andaman-&-nicobar-islands,2018,1,nicobars district,262
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143
...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688
20604,west-bengal,2024,4,paschim bardhaman district,1468252
20605,west-bengal,2024,4,nadia district,1861738
20606,west-bengal,2024,4,birbhum district,1114220
20607,west-bengal,2024,4,purba medinipur district,1717074

In [54]:
tn = "Map_user"

In [55]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Map_user' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater  \
0          0  andaman-&-nicobar-islands  2018       1
1          1  andaman-&-nicobar-islands  2018       1
2          2  andaman-&-nicobar-islands  2018       1
3          3  andaman-&-nicobar-islands  2018       2
4          4  andaman-&-nicobar-islands  2018       2
...      ...                        ...   ...     ...
20603  20603                west-bengal  2024       4
20604  20604                west-bengal  2024       4
20605  20605                west-bengal  2024       4
20606  20606                west-bengal  2024       4
20607  20607                west-bengal  2024       4

                            DistrictName  RegisteredUsers
0      north and middle andaman district              632
1                 south andaman district             5846
2                      nicobars district              262
3      north and middle andaman district              911
4                 south andaman district             8143
...                                  ...              ...
20603                alipurduar district           475688
20604         paschim bardhaman district          1468252
20605                     nadia district          1861738
20606                   birbhum district          1114220
20607           purba medinipur district          1717074

[20608 rows x 6 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Map_user' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [56]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\Top\\transaction\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'EntityType':[], 'EntityName':[], 'TransacionCount':[], 'TransacionAmount':[]}

for i in top_state_list:
    p_i=path+i+"/"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"/"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for e in list(D.get('data').keys()):
                #print(D.get('data'))
                if D.get('data').get(e):
                    for s in D.get('data').get(e):
                        # print(s.get('entityName'))
                        # print(s.get('metric').get('type'))
                        # print(s.get('metric').get('count'))
                        # print(s.get('metric').get('amount'))
                        clm['EntityName'].append(s.get('entityName'))
                        clm['EntityType'].append(e)
                        clm['TransacionCount'].append(s.get('metric').get('count'))
                        clm['TransacionAmount'].append(s.get('metric').get('amount'))
                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
                else:
                    clm['EntityName'].append(None)
                    clm['EntityType'].append(e)
                    clm['TransacionCount'].append(None)
                    clm['TransacionAmount'].append(None)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [57]:
df

,State,Year,Quater,EntityType,EntityName,TransacionCount,TransacionAmount
0,andaman-&-nicobar-islands,2018,1,states,None,NaN,NaN
1,andaman-&-nicobar-islands,2018,1,districts,south andaman,5688.0,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,districts,nicobars,528.0,1.139849e+06
3,andaman-&-nicobar-islands,2018,1,districts,north and middle andaman,442.0,9.316631e+05
4,andaman-&-nicobar-islands,2018,1,pincodes,744101,1622.0,2.769298e+06
...,...,...,...,...,...,...,...
19298,west-bengal,2024,4,pincodes,711101,6753348.0,1.049483e+10
19299,west-bengal,2024,4,pincodes,700059,6662715.0,8.009476e+09
19300,west-bengal,2024,4,pincodes,700039,6575693.0,9.018748e+09
19301,west-bengal,2024,4,pincodes,734001,6432082.0,8.996529e+09
19302,west-bengal,2024,4,pincodes,733134,6313560.0,1.050259e+10

In [58]:
tn ="Top_map"

In [59]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Top_map' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

✅ DataFrame successfully stored to table 'Top_map' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater EntityType  \
0          0  andaman-&-nicobar-islands  2018       1     states
1          1  andaman-&-nicobar-islands  2018       1  districts
2          2  andaman-&-nicobar-islands  2018       1  districts
3          3  andaman-&-nicobar-islands  2018       1  districts
4          4  andaman-&-nicobar-islands  2018       1   pincodes
...      ...                        ...   ...     ...        ...
19298  19298                west-bengal  2024       4   pincodes
19299  19299                west-bengal  2024       4   pincodes
19300  19300                west-bengal  2024       4   pincodes
19301  19301                west-bengal  2024       4   pincodes
19302  19302                west-bengal  2024       4   pincodes

                     EntityName  TransacionCount  TransacionAmount
0                          None              NaN               NaN
1                 south andaman           5688.0      1.256025e+07
2                      nicobars            528.0      1.139849e+06
3      north and middle andaman            442.0      9.316631e+05
4                        744101           1622.0      2.769298e+06
...                         ...              ...               ...
19298                    711101        6753348.0      1.049483e+10
19299                    700059        6662715.0      8.009476e+09
19300                    700039        6575693.0      9.018748e+09
19301                    734001        6432082.0      8.996529e+09
19302                    733134        6313560.0      1.050259e+10

[19303 rows x 8 columns]

In [61]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\Top\\insurance\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'EntityType':[], 'EntityName':[], 'TransacionCount':[], 'TransacionAmount':[]}

for i in top_state_list:
    p_i=path+i+"/"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"/"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for e in list(D.get('data').keys()):
                #print(D.get('data'))
                if D.get('data').get(e):
                    for s in D.get('data').get(e):
                        # print(s.get('entityName'))
                        # print(s.get('metric').get('type'))
                        # print(s.get('metric').get('count'))
                        # print(s.get('metric').get('amount'))
                        clm['EntityName'].append(s.get('entityName'))
                        clm['EntityType'].append(e)
                        clm['TransacionCount'].append(s.get('metric').get('count'))
                        clm['TransacionAmount'].append(s.get('metric').get('amount'))
                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
                else:
                    clm['EntityName'].append(None)
                    clm['EntityType'].append(e)
                    clm['TransacionCount'].append(None)
                    clm['TransacionAmount'].append(None)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [62]:
df

,State,Year,Quater,EntityType,EntityName,TransacionCount,TransacionAmount
0,andaman-&-nicobar-islands,2020,2,states,None,NaN,NaN
1,andaman-&-nicobar-islands,2020,2,districts,nicobars,3.0,565.0
2,andaman-&-nicobar-islands,2020,2,districts,south andaman,3.0,795.0
3,andaman-&-nicobar-islands,2020,2,pincodes,744301,3.0,565.0
4,andaman-&-nicobar-islands,2020,2,pincodes,744104,2.0,513.0
...,...,...,...,...,...,...,...
12959,west-bengal,2024,4,pincodes,711101,713.0,750354.0
12960,west-bengal,2024,4,pincodes,700091,642.0,969634.0
12961,west-bengal,2024,4,pincodes,700150,627.0,761501.0
12962,west-bengal,2024,4,pincodes,700039,619.0,787836.0
12963,west-bengal,2024,4,pincodes,700156,574.0,888613.0

In [63]:
tn = "Top_insurance"

In [64]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Top_insurance' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater EntityType  \
0          0  andaman-&-nicobar-islands  2020       2     states
1          1  andaman-&-nicobar-islands  2020       2  districts
2          2  andaman-&-nicobar-islands  2020       2  districts
3          3  andaman-&-nicobar-islands  2020       2   pincodes
4          4  andaman-&-nicobar-islands  2020       2   pincodes
...      ...                        ...   ...     ...        ...
12959  12959                west-bengal  2024       4   pincodes
12960  12960                west-bengal  2024       4   pincodes
12961  12961                west-bengal  2024       4   pincodes
12962  12962                west-bengal  2024       4   pincodes
12963  12963                west-bengal  2024       4   pincodes

          EntityName  TransacionCount  TransacionAmount
0               None              NaN               NaN
1           nicobars              3.0             565.0
2      south andaman              3.0             795.0
3             744301              3.0             565.0
4             744104              2.0             513.0
...              ...              ...               ...
12959         711101            713.0          750354.0
12960         700091            642.0          969634.0
12961         700150            627.0          761501.0
12962         700039            619.0          787836.0
12963         700156            574.0          888613.0

[12964 rows x 8 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Top_insurance' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [67]:
path="C:\\Users\\Aravind Kirubakaran\\OneDrive\\Desktop\\GUVI\\Project1\\PhonePay\\pulse\\data\\Top\\user\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'EntityType':[], 'EntityName':[], 'RegisteredUsers':[]}

for i in top_state_list:
    p_i=path+i+"/"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"/"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for e in list(D.get('data').keys()):
               # print(D.get('data'))
                if D.get('data').get(e):
                    for s in D.get('data').get(e):
                        # print(s.get('entityName'))
                        # print(s.get('metric').get('type'))
                        # print(s.get('metric').get('count'))
                        # print(s.get('metric').get('amount'))
                        clm['EntityName'].append(s.get('name'))
                        clm['EntityType'].append(e)
                        clm['RegisteredUsers'].append(s.get('registeredUsers'))
                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
                else:
                    clm['EntityName'].append(None)
                    clm['EntityType'].append(e)
                    clm['RegisteredUsers'].append(None)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                
#Succesfully created a dataframe
df=pd.DataFrame(clm)

In [68]:
df

,State,Year,Quater,EntityType,EntityName,RegisteredUsers
0,andaman-&-nicobar-islands,2018,1,states,None,NaN
1,andaman-&-nicobar-islands,2018,1,districts,south andaman,5846.0
2,andaman-&-nicobar-islands,2018,1,districts,north and middle andaman,632.0
3,andaman-&-nicobar-islands,2018,1,districts,nicobars,262.0
4,andaman-&-nicobar-islands,2018,1,pincodes,744103,1608.0
...,...,...,...,...,...,...
19299,west-bengal,2024,4,pincodes,733134,169596.0
19300,west-bengal,2024,4,pincodes,700059,169448.0
19301,west-bengal,2024,4,pincodes,711302,146034.0
19302,west-bengal,2024,4,pincodes,700150,142151.0
19303,west-bengal,2024,4,pincodes,711106,142077.0

In [69]:
tn = "Top_user"

In [70]:
CreateAndInsertData(tn, df)

Attempting to connect and store DataFrame...
✅ DataFrame successfully stored to table 'Top_user' in MySQL.

Data retrieved from database for verification:
       index                      State  Year  Quater EntityType  \
0          0  andaman-&-nicobar-islands  2018       1     states
1          1  andaman-&-nicobar-islands  2018       1  districts
2          2  andaman-&-nicobar-islands  2018       1  districts
3          3  andaman-&-nicobar-islands  2018       1  districts
4          4  andaman-&-nicobar-islands  2018       1   pincodes
...      ...                        ...   ...     ...        ...
19299  19299                west-bengal  2024       4   pincodes
19300  19300                west-bengal  2024       4   pincodes
19301  19301                west-bengal  2024       4   pincodes
19302  19302                west-bengal  2024       4   pincodes
19303  19303                west-bengal  2024       4   pincodes

                     EntityName  RegisteredUsers
0                          None              NaN
1                 south andaman           5846.0
2      north and middle andaman            632.0
3                      nicobars            262.0
4                        744103           1608.0
...                         ...              ...
19299                    733134         169596.0
19300                    700059         169448.0
19301                    711302         146034.0
19302                    700150         142151.0
19303                    711106         142077.0

[19304 rows x 7 columns]

C:\Users\Aravind Kirubakaran\AppData\Local\Temp\ipykernel_22320\1895172441.py:19: UserWarning: The provided table name 'Top_user' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DataFrame.to_sql(

In [1]:
df['TimeKey'] = df['Year'] * 10 + df['Quater']

# Create a string label for plotting (e.g., 'Q1 2018')
df['QuarterLabel'] = 'Q' + df['Quater'].astype(str) + ' ' + df['Year'].astype(str)

# Group by the chronological key and sum the transaction count
quarterly_trend = df.groupby(['TimeKey', 'QuarterLabel'])['TransacionCount'].sum().reset_index()

# Ensure it's sorted by the TimeKey
quarterly_trend = quarterly_trend.sort_values(by='TimeKey')

# Extract the final series for plotting
plot_data = quarterly_trend.set_index('QuarterLabel')['TransacionCount']

# --- 4. Display the result in a readable format ---
print("--- Quarterly Transaction Count Trend ---")
print(quarterly_trend[['QuarterLabel', 'TransacionCount']].to_markdown(index=False, numalign="left", stralign="left", floatfmt=",0f"))

# --- 5. Create the Line Plot ---

# Set a professional style
plt.style.use('seaborn-v0_8-darkgrid')

# Create the figure and axes
plt.figure(figsize=(14, 7))

# Plot the trend
plot_data.plot(
    kind='line',
    marker='o',
    linestyle='-',
    color='#1a759f',
    linewidth=2,
    markersize=6
)

# Add labels and title
plt.title('Total Insurance Transaction Count Trend Over Quarters', fontsize=16, pad=20)
plt.xlabel('Quarter and Year', fontsize=12)
plt.ylabel('Total Transaction Count', fontsize=12)

# Format y-axis labels to be more readable (e.g., in millions or billions)
def y_formatter(y, pos):
    if y >= 1e9:
        return f'{y*1e-9:,.1f}B'
    elif y >= 1e6:
        return f'{y*1e-6:,.1f}M'
    return f'{y:,.0f}'

plt.gca().yaxis.set_major_formatter(ticker.FuncFormatter(y_formatter))

# Improve x-axis readability by rotating labels and setting ticks
plt.xticks(rotation=45, ha='right')
plt.gca().tick_params(axis='x', which='major', labelsize=10)

# Add a grid for better readability
plt.grid(True, linestyle='--', alpha=0.7)

# Adjust layout and save the figure
plt.tight_layout()
plt.show()
plt.close()

print("\nLine plot saved as 'quarterly_transaction_count_trend.png'")

NameError: name 'df' is not defined